services:
  wordle-mysql:
    image: mysql:8.3
    container_name: wordle-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wordle2025
      MYSQL_DATABASE: wordle
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10

  wordle-app:
    build: .
    container_name: wordle-app
    restart: on-failure
    depends_on:
      wordle-mysql:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:mysql://wordle-mysql:3306/wordle?serverTimezone=Europe/Madrid
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: wordle2025
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
