name: CI/CD Pipeline

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  ci:
    name: Run Tests and SonarCloud Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: maven-

      - name: Install Chrome & ChromeDriver
        run: |
          sudo apt update
          sudo apt install -y google-chrome-stable unzip curl jq

          # Get the version of Chrome installed
          CHROME_VERSION=$(google-chrome --version | grep -oP '[0-9]+\.[0-9]+\.[0-9]+' | head -1)
          echo "Chrome version: $CHROME_VERSION"

          # Get compatible ChromeDriver version
          CHROMEDRIVER_VERSION=$(curl -sS "https://googlechromelabs.github.io/chrome-for-testing/latest-patch-versions-per-build-with-downloads.json" | jq -r ".builds[\"$CHROME_VERSION\"].version")

          if [[ -z "$CHROMEDRIVER_VERSION" ]]; then
            echo "No compatible ChromeDriver version was found for $CHROME_VERSION”
            exit 1
          fi

          echo "ChromeDriver version: $CHROMEDRIVER_VERSION"

          # Download ChromeDriver
          curl -sS -o chromedriver.zip "https://storage.googleapis.com/chrome-for-testing-public/$CHROMEDRIVER_VERSION/linux64/chromedriver-linux64.zip"

          # Check if the download was successful
          if ! unzip -tq chromedriver.zip; then
            echo "Error: El archivo descargado no es un ZIP válido"
            exit 1
          fi

          # Extract and move ChromeDriver
          sudo unzip chromedriver.zip -d /usr/local/bin/
          sudo rm -f /usr/local/bin/chromedriver-linux64/LICENSE.chromedriver /usr/local/bin/chromedriver-linux64/THIRD_PARTY_NOTICES.chromedriver
          sudo mv /usr/local/bin/chromedriver-linux64/chromedriver /usr/local/bin/chromedriver
          sudo chmod +x /usr/local/bin/chromedriver
          rm -r chromedriver.zip /usr/local/bin/chromedriver-linux64

          # Verify the installation
          chromedriver --version

      - name: Run tests
        run: mvn test

      - name: Build and analyze with SonarCloud
        run: |
          mvn clean verify sonar:sonar \
            -Dsonar.projectKey=M-Serral_WordleApp \
            -Dsonar.organization=m-serral \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=${{ secrets.SONARCLOUD_TOKEN }}

      - name: Upload Sonar Report
        uses: actions/upload-artifact@v4
        with:
          name: SonarQube Report
          path: sonar_report.json

  cd:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: ci # Only executed if the job “ci” passes correctly
    if: github.event_name == 'push' # Just run this job in push to master

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Get project version from pom.xml
        run: echo "VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV

      - name: Build Docker Image
        run: docker build -t mserral/wordleapp:${{ env.VERSION }} .

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Push Docker Image
        run: docker push mserral/wordleapp:${{ env.VERSION }}
