name: CI Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: maven-

      - name: Install Chrome & ChromeDriver
        run: |
          sudo apt update
          sudo apt install -y google-chrome-stable unzip curl

          # Obtener la versión de Chrome instalada
          CHROME_VERSION=$(google-chrome --version | grep -oP '[0-9]+\.[0-9]+\.[0-9]+' | head -1)
          echo "Chrome version: $CHROME_VERSION"

          # Obtener la versión de ChromeDriver compatible
          CHROMEDRIVER_VERSION=$(curl -sS "https://googlechromelabs.github.io/chrome-for-testing/latest-patch-versions-per-build-with-downloads.json" | jq -r ".builds[\"$CHROME_VERSION\"].version")

          if [[ -z "$CHROMEDRIVER_VERSION" ]]; then
            echo "Error: No se encontró una versión de ChromeDriver compatible para $CHROME_VERSION"
            exit 1
          fi

          echo "ChromeDriver version: $CHROMEDRIVER_VERSION"

          # Descargar ChromeDriver
          curl -sS -o chromedriver.zip "https://storage.googleapis.com/chrome-for-testing-public/$CHROMEDRIVER_VERSION/linux64/chromedriver-linux64.zip"

          # Verificar si la descarga fue exitosa
          if ! unzip -tq chromedriver.zip; then
            echo "Error: El archivo descargado no es un ZIP válido"
            exit 1
          fi

          # Extraer y mover ChromeDriver
          sudo unzip chromedriver.zip -d /usr/local/bin/
          sudo mv /usr/local/bin/chromedriver-linux64/chromedriver /usr/local/bin/chromedriver
          sudo chmod +x /usr/local/bin/chromedriver
          rm -r chromedriver.zip /usr/local/bin/chromedriver-linux64

          # Verificar la instalación
          chromedriver --version

      - name: Run tests
        run: mvn test

      - name: Build and analyze with SonarCloud
        run: |
          mvn clean verify sonar:sonar \
            -Dsonar.projectKey=M-Serral_WordleApp \
            -Dsonar.organization=m-serral \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=${{ secrets.SONARCLOUD_TOKEN }}

      - name: Download SonarCloud Report
        run: |
          curl -s -u ${{ secrets.SONARCLOUD_TOKEN }} \
          "https://sonarcloud.io/api/measures/component?component=M-Serral_WordleApp&metricKeys=coverage,bugs,vulnerabilities,code_smells" -o sonar_report.json

      - name: Upload Sonar Report
        uses: actions/upload-artifact@v4
        with:
          name: SonarQube Report
          path: sonar_report.json
